use_frameworks!

platform :ios, '9.0'

target 'CustomPod_Example_Axon_Example' do
  pod 'CustomPod_Example_Axon', :path => '../'

  target 'CustomPod_Example_Axon_Tests' do
    inherit! :search_paths

    
  end
end
